import UIKit

protocol HomeWireframeInterface: WireframeInterface {
    func showVStack()
    func showZStack()
    func showContentView()
    func showColorPicker()
    func showRectangle()
    func showSection()
    func showHStack()
    func showNavigationStack()
    func showFrame()
    func showScrollView()
    func showNavigationView()
    func showTransaction()
    func showLazyHGrid()
    func showLazyVStackView()
    func showMatchedGeometryEffect()
    func showImage()
    func showMenuButton()
    func showCircle()
    func showOpacity()
    func showSecureField()
    func showContextMenu()
    func showBinding()
    func showStepper()
    func showLazyVGridView()
    func showCanvas()
    func showEllipse()
    func showPadding()
}
